name: Actualizar listado de PDFs

on:
  push:
    branches:
      - main

jobs:
  update_pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install --upgrade pip

      - name: Ejecutar script de Python
        run: python generar_index.py

      - name: Subir cambios a GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Actualizar listado de PDFs"
          git push
